apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: development
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: mongodb
          image: mongo
          imagePullPolicy: Always
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/k8-test/admin/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: /etc/k8-test/admin/MONGO_ROOT_PASSWORD
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
            - name: k8-test
              mountPath: /etc/k8-test
              readOnly: true
            - name: mongodb-scripts
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
            - name: mongodb-configmap
              mountPath: /config
              readOnly: true
      volumes:
        - name: k8-test
          secret:
            secretName: mongodb-secret
            items:
              - key: MONGO_ROOT_USERNAME
                path: admin/MONGO_ROOT_USERNAME
              - key: MONGO_ROOT_PASSWORD
                path: admin/MONGO_ROOT_PASSWORD
              - key: MONGO_USERNAME
                path: MONGO_USERNAME
              - key: MONGO_PASSWORD
                path: MONGO_PASSWORD
              - key: MONGO_USERS_LIST
                path: MONGO_USERS_LIST
        - name: mongodb-scripts
          configMap:
            name: mongodb-configmap
            items:
              - key: ensure-users.js
                path: ensure-users.js
        - name: mongodb-configmap
          configMap:
            name: mongodb-configmap
            items:
              - key: mongo.conf
                path: mongo.conf
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
